### PR TITLE
add some documentation

### PR DESCRIPTION
**Pull request by vladikoff**

### CODE REVIEW

**Comment by jgraham** [comment]
Thanks for the patch!

Review is on critic.

**Comment by vladikoff** [comment]
@jgraham fixed it up, let me know what other buttons to press

**Comment by jgraham** [comment]
Reviewed. Mind squashing into one commit before I merge (with critic it's best to do this after the review is done, hence the warning above).

**Comment by vladikoff** [comment]
Done.

**Comment by jgraham** [comment]
Thanks!

**Pull request merged**
