### PR TITLE
Adding a new command line argument e10s profile

### PR DESCRIPTION
**Pull request by martiansideofthemoon**
@jgraham this is the first half of the first part of #43 . Is it alright? I've added a new command line option.

---
This change is [Review on Reviewable](https://reviewable.io/reviews/jgraham/wires/51)

### CODE REVIEW

**Comment by jgraham** [comment]
You need to also implement the code that reads this pref and starts Fx with e10s enabled as part of this PR.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main.rs, line 84 \[r1\]](https://reviewable.io:443/reviews/jgraham/wires/51#-KCQbwVH_uo2v6SKXQu_:-KCQbwVIPVy2SyfsYA7v:852919288) ([raw file](https://github.com/jgraham/wires/blob/ae66c837eb345716fbfec94263922808146430bb/src/main.rs#L84)):*
Remove debugging code.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wires/51#-:-KCQbz9_aD93taM9qwNE:179079598)*

**Comment by jgraham** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main.rs, line 13 \[r2\]](https://reviewable.io:443/reviews/jgraham/wires/51#-KCRSjfKFxJhlq3zACMn:-KCRSjfKFxJhlq3zACMo:-1498011509) ([raw file](https://github.com/jgraham/wires/blob/22580c0941e4057bac4834a9c0597b4e560e9b18/src/main.rs#L13)):*
I think this is unused?

---

*[src/main.rs, line 75 \[r2\]](https://reviewable.io:443/reviews/jgraham/wires/51#-KCRScyENsBhtl5pKrEO:-KCRScyFHIYjHBIYQ5EN:1827958646) ([raw file](https://github.com/jgraham/wires/blob/22580c0941e4057bac4834a9c0597b4e560e9b18/src/main.rs#L75)):*
Call this `--e10s`

---

*[src/marionette.rs, line 156 \[r2\]](https://reviewable.io:443/reviews/jgraham/wires/51#-KCRU8jT7j-uFTaqxUM3:-KCRU8jUfd7MHLMVGbrO:-61396115) ([raw file](https://github.com/jgraham/wires/blob/22580c0941e4057bac4834a9c0597b4e560e9b18/src/marionette.rs#L156)):*
I'm pretty sure you just want to set `browser.tabs.remote.autostart` (but you want to set `.2` to `false` to ensure e10s is disabled). From the code it looks like `.1` doesn't exist anymore, the unsuffixed version represents user opt-in and `.2` represents the default value (https://dxr.mozilla.org/mozilla-central/source/toolkit/xre/nsAppRunner.cpp#4726) 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wires/51)*

**Comment by martiansideofthemoon** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/marionette.rs, line 156 \[r2\]](https://reviewable.io:443/reviews/jgraham/wires/51#-KCRU8jT7j-uFTaqxUM3:-KCS7b0iJ4zFT6r87GSh:-1752709405) ([raw file](https://github.com/jgraham/wires/blob/22580c0941e4057bac4834a9c0597b4e560e9b18/src/marionette.rs#L156)):*
Haven't I added it a few lines below in a new array `NON_E10S_PREFERENCES` ?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wires/51)*

**Comment by jgraham** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/marionette.rs, line 156 \[r2\]](https://reviewable.io:443/reviews/jgraham/wires/51#-KCRU8jT7j-uFTaqxUM3:-KCSJGBrs-iJArXemrKL:-30124799) ([raw file](https://github.com/jgraham/wires/blob/22580c0941e4057bac4834a9c0597b4e560e9b18/src/marionette.rs#L156)):*
My point is that there's too much here, and not enough below. It should be something like:


    pub static E10S_PREFERENCES: [(&'static str, PrefValue); 1] = [
        ("browser.tabs.remote.autostart", PrefValue::PrefBool(true)),
    ];

    pub static NON_E10S_PREFERENCES: [(&'static str, PrefValue); 2] = [
        ("browser.tabs.remote.autostart", PrefValue::PrefBool(false)),
        ("browser.tabs.remote.autostart.2", PrefValue::PrefBool(false))
    ];

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wires/51)*

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jgraham/wires/51)*

**Pull request merged**
